server:
  port: 8080
spring:
  application:
    name: zuul-service

##路由配置
zuul:
  routes:
    #以商品微服务
    #product-service: #路由id，随便写
    #  path: /product-service/** #映射路径 #localhost:8080/product-service/xxx
    #  url: http://127.0.0.1:8090 #映射路径对应的实际微服务url地址
    #  serviceId: product-service #配置转发的微服务的服务名称
    # 如果 路由id 和 对应的微服务的serviceId一致的话
    product-service: /product-service/**
    # zuul中的默认路由配置
    # 如果当前的微服务名称service-product,默认的请求映射路径 /service-product/**
    order-service: /order-service/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/ #,http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true #使用ip地址注册