server:
  port: 9090


#  配置数据库
spring:
  application:
    name: order-service-feign
  datasource:
    password: 1234
    username: root
    url: jdbc:mysql://localhost:3306/shop
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
    map-underscore-to-camel-case: true

  global-config:
    db-config:
      id-type: auto
  type-aliases-package: classpath:cn.itcast.order.entity

#配置Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/ #,http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true #使用ip地址注册

management:
  endpoint:
    hystrix:
      stream:
        enabled: true



hystrix:
  command:
     default:
       execution:
         isolation:
           strategy: ExecutionIsolationStrategy.SEMAPHORE # 信号量隔离级别
                     # ExecutionIsolationStrategy.THREAD 线程池隔离
           thread:
             timeoutInMilliseconds: 3000 # 默认的连接超时时间1秒，若1秒没有返回数据，自动的触发降级逻辑
       circuitBreaker:
         requestVolumeThredshold: 5 #触发熔断的最小请求次数，默认20 /10秒
         sleepWindowInMilliseconds: 10000 #熔断多少秒后去尝试请求 默认5秒 打开状态的时间
         errorThresholdPercentage: 50 # 触发熔断的是啊比请求最小占比，默认50%

