server:
  port: 8080


#  配置数据库
spring:
  application:
    name: product_service
  datasource:
    password: 1234
    username: root
    url: jdbc:mysql://localhost:3306/shop
    driver-class-name: com.mysql.jdbc.Driver


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
    map-underscore-to-camel-case: true

  global-config:
    db-config:
      id-type: auto
  type-aliases-package: classpath:cn.itcast.product.entity


#配置Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/ , http://localhost:8000/eureka/ #多个eurekaserver之间用逗号隔开
  instance:
    prefer-ip-address: true #使用ip地址注册

